/*
Magma - C++1x interface over Khronos Vulkan API.
Copyright (C) 2018 Victor Coda.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
*/
#include "stringize.h"

#ifdef MAGMA_DEBUG
#define MAGMA_DEFAULT_UNKNOWN default: return MAGMA_UNKNOWN

namespace magma
{
MAGMA_STRING stringize(VkSystemAllocationScope param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_SYSTEM_ALLOCATION_SCOPE_COMMAND);
    MAGMA_STRINGIZE_FIELD(VK_SYSTEM_ALLOCATION_SCOPE_OBJECT);
    MAGMA_STRINGIZE_FIELD(VK_SYSTEM_ALLOCATION_SCOPE_CACHE);
    MAGMA_STRINGIZE_FIELD(VK_SYSTEM_ALLOCATION_SCOPE_DEVICE);
    MAGMA_STRINGIZE_FIELD(VK_SYSTEM_ALLOCATION_SCOPE_INSTANCE);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkInternalAllocationType param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_INTERNAL_ALLOCATION_TYPE_EXECUTABLE);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkFormat param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_UNDEFINED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R4G4_UNORM_PACK8);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R4G4B4A4_UNORM_PACK16);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B4G4R4A4_UNORM_PACK16);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R5G6B5_UNORM_PACK16);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B5G6R5_UNORM_PACK16);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R5G5B5A1_UNORM_PACK16);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B5G5R5A1_UNORM_PACK16);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A1R5G5B5_UNORM_PACK16);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8_SNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8_USCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8_SSCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8_SRGB);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8_SNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8_USCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8_SSCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8_SRGB);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8_SNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8_USCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8_SSCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8_SRGB);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8_SNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8_USCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8_SSCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8_SRGB);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8A8_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8A8_SNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8A8_USCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8A8_SSCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8A8_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8A8_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R8G8B8A8_SRGB);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8A8_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8A8_SNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8A8_USCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8A8_SSCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8A8_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8A8_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8A8_SRGB);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A8B8G8R8_UNORM_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A8B8G8R8_SNORM_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A8B8G8R8_USCALED_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A8B8G8R8_SSCALED_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A8B8G8R8_UINT_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A8B8G8R8_SINT_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A8B8G8R8_SRGB_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2R10G10B10_UNORM_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2R10G10B10_SNORM_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2R10G10B10_USCALED_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2R10G10B10_SSCALED_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2R10G10B10_UINT_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2R10G10B10_SINT_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2B10G10R10_UNORM_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2B10G10R10_SNORM_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2B10G10R10_USCALED_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2B10G10R10_SSCALED_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2B10G10R10_UINT_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_A2B10G10R10_SINT_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16_SNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16_USCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16_SSCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16_SNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16_USCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16_SSCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16_SNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16_USCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16_SSCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16A16_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16A16_SNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16A16_USCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16A16_SSCALED);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16A16_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16A16_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R16G16B16A16_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32G32_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32G32_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32G32_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32G32B32_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32G32B32_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32G32B32_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32G32B32A32_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32G32B32A32_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R32G32B32A32_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64G64_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64G64_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64G64_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64G64B64_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64G64B64_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64G64B64_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64G64B64A64_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64G64B64A64_SINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R64G64B64A64_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B10G11R11_UFLOAT_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_E5B9G9R9_UFLOAT_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_D16_UNORM);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_X8_D24_UNORM_PACK32);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_D32_SFLOAT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_S8_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_D16_UNORM_S8_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_D24_UNORM_S8_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_D32_SFLOAT_S8_UINT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC1_RGB_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC1_RGB_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC1_RGBA_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC1_RGBA_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC2_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC2_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC3_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC3_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC4_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC4_SNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC5_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC5_SNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC6H_UFLOAT_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC6H_SFLOAT_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC7_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_BC7_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_EAC_R11_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_EAC_R11_SNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_EAC_R11G11_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_EAC_R11G11_SNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_4x4_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_4x4_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_5x4_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_5x4_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_5x5_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_5x5_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_6x5_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_6x5_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_6x6_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_6x6_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_8x5_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_8x5_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_8x6_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_8x6_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_8x8_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_8x8_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_10x5_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_10x5_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_10x6_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_10x6_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_10x8_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_10x8_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_10x10_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_10x10_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_12x10_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_12x10_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_12x12_UNORM_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_ASTC_12x12_SRGB_BLOCK);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G8B8G8R8_422_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B8G8R8G8_422_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R10X6_UNORM_PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R12X4_UNORM_PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G16B16G16R16_422_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_B16G16R16G16_422_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkImageType param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_TYPE_1D);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_TYPE_2D);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_TYPE_3D);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkImageTiling param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_TILING_OPTIMAL);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_TILING_LINEAR);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkPhysicalDeviceType param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_PHYSICAL_DEVICE_TYPE_OTHER);
    MAGMA_STRINGIZE_FIELD(VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU);
    MAGMA_STRINGIZE_FIELD(VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU);
    MAGMA_STRINGIZE_FIELD(VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU);
    MAGMA_STRINGIZE_FIELD(VK_PHYSICAL_DEVICE_TYPE_CPU);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkQueryType param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_QUERY_TYPE_OCCLUSION);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_TYPE_PIPELINE_STATISTICS);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_TYPE_TIMESTAMP);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkSharingMode param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_SHARING_MODE_EXCLUSIVE);
    MAGMA_STRINGIZE_FIELD(VK_SHARING_MODE_CONCURRENT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkImageLayout param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_UNDEFINED);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_GENERAL);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_PREINITIALIZED);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_PRESENT_SRC_KHR);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkImageViewType param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_VIEW_TYPE_1D);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_VIEW_TYPE_2D);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_VIEW_TYPE_3D);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_VIEW_TYPE_CUBE);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_VIEW_TYPE_1D_ARRAY);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_VIEW_TYPE_2D_ARRAY);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_VIEW_TYPE_CUBE_ARRAY);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkComponentSwizzle param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_COMPONENT_SWIZZLE_IDENTITY);
    MAGMA_STRINGIZE_FIELD(VK_COMPONENT_SWIZZLE_ZERO);
    MAGMA_STRINGIZE_FIELD(VK_COMPONENT_SWIZZLE_ONE);
    MAGMA_STRINGIZE_FIELD(VK_COMPONENT_SWIZZLE_R);
    MAGMA_STRINGIZE_FIELD(VK_COMPONENT_SWIZZLE_G);
    MAGMA_STRINGIZE_FIELD(VK_COMPONENT_SWIZZLE_B);
    MAGMA_STRINGIZE_FIELD(VK_COMPONENT_SWIZZLE_A);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkVertexInputRate param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_VERTEX_INPUT_RATE_VERTEX);
    MAGMA_STRINGIZE_FIELD(VK_VERTEX_INPUT_RATE_INSTANCE);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkPrimitiveTopology param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_POINT_LIST);
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_LINE_LIST);
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_LINE_STRIP);
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST);
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP);
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN);
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY);
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY);
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY);
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY);
    MAGMA_STRINGIZE_FIELD(VK_PRIMITIVE_TOPOLOGY_PATCH_LIST);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkPolygonMode param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_POLYGON_MODE_FILL);
    MAGMA_STRINGIZE_FIELD(VK_POLYGON_MODE_LINE);
    MAGMA_STRINGIZE_FIELD(VK_POLYGON_MODE_POINT);
    MAGMA_STRINGIZE_FIELD(VK_POLYGON_MODE_FILL_RECTANGLE_NV);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkFrontFace param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_FRONT_FACE_COUNTER_CLOCKWISE);
    MAGMA_STRINGIZE_FIELD(VK_FRONT_FACE_CLOCKWISE);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkCompareOp param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_COMPARE_OP_NEVER);
    MAGMA_STRINGIZE_FIELD(VK_COMPARE_OP_LESS);
    MAGMA_STRINGIZE_FIELD(VK_COMPARE_OP_EQUAL);
    MAGMA_STRINGIZE_FIELD(VK_COMPARE_OP_LESS_OR_EQUAL);
    MAGMA_STRINGIZE_FIELD(VK_COMPARE_OP_GREATER);
    MAGMA_STRINGIZE_FIELD(VK_COMPARE_OP_NOT_EQUAL);
    MAGMA_STRINGIZE_FIELD(VK_COMPARE_OP_GREATER_OR_EQUAL);
    MAGMA_STRINGIZE_FIELD(VK_COMPARE_OP_ALWAYS);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkStencilOp param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_OP_KEEP);
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_OP_ZERO);
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_OP_REPLACE);
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_OP_INCREMENT_AND_CLAMP);
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_OP_DECREMENT_AND_CLAMP);
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_OP_INVERT);
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_OP_INCREMENT_AND_WRAP);
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_OP_DECREMENT_AND_WRAP);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkLogicOp param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_CLEAR);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_AND);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_AND_REVERSE);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_COPY);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_AND_INVERTED);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_NO_OP);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_XOR);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_OR);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_NOR);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_EQUIVALENT);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_INVERT);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_OR_REVERSE);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_COPY_INVERTED);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_OR_INVERTED);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_NAND);
    MAGMA_STRINGIZE_FIELD(VK_LOGIC_OP_SET);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkBlendFactor param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_ZERO);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_ONE);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_SRC_COLOR);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_DST_COLOR);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_SRC_ALPHA);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_DST_ALPHA);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_CONSTANT_COLOR);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_CONSTANT_ALPHA);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_SRC_ALPHA_SATURATE);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_SRC1_COLOR);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_SRC1_ALPHA);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkBlendOp param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_ADD);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_SUBTRACT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_REVERSE_SUBTRACT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_MIN);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_MAX);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_ZERO_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_SRC_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_DST_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_SRC_OVER_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_DST_OVER_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_SRC_IN_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_DST_IN_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_SRC_OUT_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_DST_OUT_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_SRC_ATOP_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_DST_ATOP_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_XOR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_MULTIPLY_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_SCREEN_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_OVERLAY_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_DARKEN_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_LIGHTEN_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_COLORDODGE_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_COLORBURN_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_HARDLIGHT_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_SOFTLIGHT_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_DIFFERENCE_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_EXCLUSION_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_INVERT_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_INVERT_RGB_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_LINEARDODGE_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_LINEARBURN_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_VIVIDLIGHT_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_LINEARLIGHT_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_PINLIGHT_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_HARDMIX_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_HSL_HUE_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_HSL_SATURATION_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_HSL_COLOR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_HSL_LUMINOSITY_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_PLUS_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_PLUS_CLAMPED_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_PLUS_DARKER_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_MINUS_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_MINUS_CLAMPED_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_CONTRAST_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_INVERT_OVG_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_RED_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_GREEN_EXT);
    MAGMA_STRINGIZE_FIELD(VK_BLEND_OP_BLUE_EXT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkDynamicState param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_VIEWPORT);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_SCISSOR);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_LINE_WIDTH);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_DEPTH_BIAS);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_BLEND_CONSTANTS);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_DEPTH_BOUNDS);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_STENCIL_WRITE_MASK);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_STENCIL_REFERENCE);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT);
    MAGMA_STRINGIZE_FIELD(VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkFilter param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_FILTER_NEAREST);
    MAGMA_STRINGIZE_FIELD(VK_FILTER_LINEAR);
    MAGMA_STRINGIZE_FIELD(VK_FILTER_CUBIC_IMG);
    MAGMA_DEFAULT_UNKNOWN;
    };
}
    
MAGMA_STRING stringize(VkSamplerMipmapMode param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_SAMPLER_MIPMAP_MODE_NEAREST);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLER_MIPMAP_MODE_LINEAR);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkSamplerAddressMode param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_SAMPLER_ADDRESS_MODE_REPEAT);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkBorderColor param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK);
    MAGMA_STRINGIZE_FIELD(VK_BORDER_COLOR_INT_TRANSPARENT_BLACK);
    MAGMA_STRINGIZE_FIELD(VK_BORDER_COLOR_FLOAT_OPAQUE_BLACK);
    MAGMA_STRINGIZE_FIELD(VK_BORDER_COLOR_INT_OPAQUE_BLACK);
    MAGMA_STRINGIZE_FIELD(VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE);
    MAGMA_STRINGIZE_FIELD(VK_BORDER_COLOR_INT_OPAQUE_WHITE);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkDescriptorType param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_SAMPLER);
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER);
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE);
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_STORAGE_IMAGE);
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER);
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER);
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER);
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_STORAGE_BUFFER);
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC);
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC);
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkAttachmentLoadOp param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_ATTACHMENT_LOAD_OP_LOAD);
    MAGMA_STRINGIZE_FIELD(VK_ATTACHMENT_LOAD_OP_CLEAR);
    MAGMA_STRINGIZE_FIELD(VK_ATTACHMENT_LOAD_OP_DONT_CARE);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkAttachmentStoreOp param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_ATTACHMENT_STORE_OP_STORE);
    MAGMA_STRINGIZE_FIELD(VK_ATTACHMENT_STORE_OP_DONT_CARE);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkPipelineBindPoint param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_BIND_POINT_GRAPHICS);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_BIND_POINT_COMPUTE);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkCommandBufferLevel param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_COMMAND_BUFFER_LEVEL_PRIMARY);
    MAGMA_STRINGIZE_FIELD(VK_COMMAND_BUFFER_LEVEL_SECONDARY);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkIndexType param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_INDEX_TYPE_UINT16);
    MAGMA_STRINGIZE_FIELD(VK_INDEX_TYPE_UINT32);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkSubpassContents param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_SUBPASS_CONTENTS_INLINE);
    MAGMA_STRINGIZE_FIELD(VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkObjectType param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_UNKNOWN);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_INSTANCE);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_PHYSICAL_DEVICE);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_DEVICE);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_QUEUE);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_SEMAPHORE);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_COMMAND_BUFFER);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_FENCE);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_DEVICE_MEMORY);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_BUFFER);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_IMAGE);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_EVENT);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_QUERY_POOL);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_BUFFER_VIEW);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_IMAGE_VIEW);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_SHADER_MODULE);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_PIPELINE_CACHE);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_PIPELINE_LAYOUT);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_RENDER_PASS);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_PIPELINE);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_SAMPLER);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_DESCRIPTOR_POOL);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_DESCRIPTOR_SET);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_FRAMEBUFFER);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_COMMAND_POOL);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_SURFACE_KHR);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_SWAPCHAIN_KHR);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_DISPLAY_KHR);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_DISPLAY_MODE_KHR);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_KHR);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_OBJECT_TABLE_NVX );
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVX);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR);
    MAGMA_STRINGIZE_FIELD(VK_OBJECT_TYPE_VALIDATION_CACHE_EXT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkFormatFeatureFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_BLIT_SRC_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_BLIT_DST_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_TRANSFER_SRC_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_TRANSFER_DST_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_DISJOINT_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkImageUsageFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_USAGE_TRANSFER_SRC_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_USAGE_TRANSFER_DST_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_USAGE_SAMPLED_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_USAGE_STORAGE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkImageCreateFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_SPARSE_BINDING_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_SPARSE_ALIASED_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_ALIAS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_EXTENDED_USAGE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_PROTECTED_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_DISJOINT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_CREATE_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_BIT_EXT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkSampleCountFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_SAMPLE_COUNT_1_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLE_COUNT_2_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLE_COUNT_4_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLE_COUNT_8_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLE_COUNT_16_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLE_COUNT_32_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SAMPLE_COUNT_64_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkQueueFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_QUEUE_GRAPHICS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUEUE_COMPUTE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUEUE_TRANSFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUEUE_SPARSE_BINDING_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkMemoryPropertyFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    MAGMA_STRINGIZE_FIELD(VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_MEMORY_PROPERTY_HOST_CACHED_BIT);
    MAGMA_STRINGIZE_FIELD(VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkMemoryHeapFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_MEMORY_HEAP_DEVICE_LOCAL_BIT);
    MAGMA_STRINGIZE_FIELD(VK_MEMORY_HEAP_MULTI_INSTANCE_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkDeviceQueueCreateFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkPipelineStageFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_VERTEX_INPUT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_VERTEX_SHADER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_TRANSFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_HOST_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_ALL_COMMANDS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkImageAspectFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_ASPECT_COLOR_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_ASPECT_DEPTH_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_ASPECT_STENCIL_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_ASPECT_METADATA_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_ASPECT_PLANE_0_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_ASPECT_PLANE_1_BIT);
    MAGMA_STRINGIZE_FIELD(VK_IMAGE_ASPECT_PLANE_2_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkSparseImageFormatFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkSparseMemoryBindFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_SPARSE_MEMORY_BIND_METADATA_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkFenceCreateFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_FENCE_CREATE_SIGNALED_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkQueryPipelineStatisticFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkQueryResultFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_QUERY_RESULT_64_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_RESULT_WAIT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_RESULT_WITH_AVAILABILITY_BIT);
    MAGMA_STRINGIZE_FIELD(VK_QUERY_RESULT_PARTIAL_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkBufferCreateFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_CREATE_SPARSE_BINDING_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_CREATE_SPARSE_ALIASED_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_CREATE_PROTECTED_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkBufferUsageFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_USAGE_TRANSFER_SRC_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_USAGE_TRANSFER_DST_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_USAGE_STORAGE_BUFFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_USAGE_INDEX_BUFFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_USAGE_VERTEX_BUFFER_BIT);
    MAGMA_STRINGIZE_FIELD(VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkPipelineCreateFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT);
    MAGMA_STRINGIZE_FIELD(VK_PIPELINE_CREATE_DERIVATIVE_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkShaderStageFlagBits flags) noexcept
{
    switch (flags)
    {
    MAGMA_STRINGIZE_FIELD(VK_SHADER_STAGE_VERTEX_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SHADER_STAGE_GEOMETRY_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SHADER_STAGE_FRAGMENT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SHADER_STAGE_COMPUTE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_SHADER_STAGE_ALL_GRAPHICS);
    MAGMA_STRINGIZE_FIELD(VK_SHADER_STAGE_ALL);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkCullModeFlagBits flags) noexcept
{
    switch (flags)
    {
    MAGMA_STRINGIZE_FIELD(VK_CULL_MODE_NONE);
    MAGMA_STRINGIZE_FIELD(VK_CULL_MODE_FRONT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_CULL_MODE_BACK_BIT);
    MAGMA_STRINGIZE_FIELD(VK_CULL_MODE_FRONT_AND_BACK); 
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkColorComponentFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_COLOR_COMPONENT_R_BIT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_COMPONENT_G_BIT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_COMPONENT_B_BIT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_COMPONENT_A_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkDescriptorSetLayoutCreateFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkDescriptorPoolCreateFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkAttachmentDescriptionFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkAccessFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_INDIRECT_COMMAND_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_INDEX_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_UNIFORM_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_INPUT_ATTACHMENT_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_SHADER_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_SHADER_WRITE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_COLOR_ATTACHMENT_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_TRANSFER_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_TRANSFER_WRITE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_HOST_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_HOST_WRITE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_MEMORY_READ_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_MEMORY_WRITE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_COMMAND_PROCESS_READ_BIT_NVX);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_COMMAND_PROCESS_WRITE_BIT_NVX);
    MAGMA_STRINGIZE_FIELD(VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkCommandPoolCreateFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_COMMAND_POOL_CREATE_TRANSIENT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkCommandPoolResetFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkCommandBufferUsageFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT);
    MAGMA_STRINGIZE_FIELD(VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkQueryControlFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_QUERY_CONTROL_PRECISE_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkCommandBufferResetFlagBits bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkStencilFaceFlagBits flags) noexcept
{
    switch (flags)
    {
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_FACE_FRONT_BIT);
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_FACE_BACK_BIT);
    MAGMA_STRINGIZE_FIELD(VK_STENCIL_FRONT_AND_BACK);
    MAGMA_DEFAULT_UNKNOWN;
    }
}

MAGMA_STRING stringize(VkColorSpaceKHR param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_SRGB_NONLINEAR_KHR);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_DCI_P3_LINEAR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_BT709_LINEAR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_BT709_NONLINEAR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_BT2020_LINEAR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_HDR10_ST2084_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_DOLBYVISION_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_HDR10_HLG_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_PASS_THROUGH_EXT);
    MAGMA_STRINGIZE_FIELD(VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkPresentModeKHR param) noexcept
{
    switch (param)
    {
    MAGMA_STRINGIZE_FIELD(VK_PRESENT_MODE_IMMEDIATE_KHR);
    MAGMA_STRINGIZE_FIELD(VK_PRESENT_MODE_MAILBOX_KHR);
    MAGMA_STRINGIZE_FIELD(VK_PRESENT_MODE_FIFO_KHR);
    MAGMA_STRINGIZE_FIELD(VK_PRESENT_MODE_FIFO_RELAXED_KHR);
    MAGMA_STRINGIZE_FIELD(VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR);
    MAGMA_STRINGIZE_FIELD(VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkSurfaceTransformFlagBitsKHR bit) noexcept 
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR);
    MAGMA_DEFAULT_UNKNOWN;
    };
}

MAGMA_STRING stringize(VkCompositeAlphaFlagBitsKHR bit) noexcept
{
    switch (bit)
    {
    MAGMA_STRINGIZE_FIELD(VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR);
    MAGMA_STRINGIZE_FIELD(VK_COMPOSITE_ALPHA_FLAG_BITS_MAX_ENUM_KHR);
    MAGMA_DEFAULT_UNKNOWN;
    };
}
} // namespace magma

#endif // MAGMA_DEBUG
