#pragma once

namespace magma
{
namespace helpers
{
constexpr VkDebugReportObjectTypeEXT castToDebugReportType(VkObjectType objectType) noexcept
{
    switch (objectType)
    {
    case VK_OBJECT_TYPE_UNKNOWN:
        return VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT;
    case VK_OBJECT_TYPE_INSTANCE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_INSTANCE_EXT;
    case VK_OBJECT_TYPE_PHYSICAL_DEVICE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_PHYSICAL_DEVICE_EXT;
    case VK_OBJECT_TYPE_DEVICE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT;
    case VK_OBJECT_TYPE_QUEUE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_QUEUE_EXT;
    case VK_OBJECT_TYPE_SEMAPHORE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_SEMAPHORE_EXT;
    case VK_OBJECT_TYPE_COMMAND_BUFFER:
        return VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT;
    case VK_OBJECT_TYPE_FENCE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_FENCE_EXT;
    case VK_OBJECT_TYPE_DEVICE_MEMORY:
        return VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXT;
    case VK_OBJECT_TYPE_BUFFER:
        return VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_EXT;
    case VK_OBJECT_TYPE_IMAGE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT;
    case VK_OBJECT_TYPE_EVENT:
        return VK_DEBUG_REPORT_OBJECT_TYPE_EVENT_EXT;
    case VK_OBJECT_TYPE_QUERY_POOL:
        return VK_DEBUG_REPORT_OBJECT_TYPE_QUERY_POOL_EXT;
    case VK_OBJECT_TYPE_BUFFER_VIEW:
        return VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_VIEW_EXT;
    case VK_OBJECT_TYPE_IMAGE_VIEW:
        return VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_VIEW_EXT;
    case VK_OBJECT_TYPE_SHADER_MODULE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT;
    case VK_OBJECT_TYPE_PIPELINE_CACHE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_CACHE_EXT;
    case VK_OBJECT_TYPE_PIPELINE_LAYOUT:
        return VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_LAYOUT_EXT;
    case VK_OBJECT_TYPE_RENDER_PASS:
        return VK_DEBUG_REPORT_OBJECT_TYPE_RENDER_PASS_EXT;
    case VK_OBJECT_TYPE_PIPELINE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_EXT;
    case VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT:
        return VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT_EXT;
    case VK_OBJECT_TYPE_SAMPLER:
        return VK_DEBUG_REPORT_OBJECT_TYPE_SAMPLER_EXT;
    case VK_OBJECT_TYPE_DESCRIPTOR_POOL:
        return VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_POOL_EXT;
    case VK_OBJECT_TYPE_DESCRIPTOR_SET:
        return VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_EXT;
    case VK_OBJECT_TYPE_FRAMEBUFFER:
        return VK_DEBUG_REPORT_OBJECT_TYPE_FRAMEBUFFER_EXT;
    case VK_OBJECT_TYPE_COMMAND_POOL:
        return VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_POOL_EXT;
    case VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION:
        return VK_DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR_EXT;
    case VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE:
        return VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_EXT;
    // Non-core types
    case VK_OBJECT_TYPE_SURFACE_KHR:
        return VK_DEBUG_REPORT_OBJECT_TYPE_SURFACE_KHR_EXT;
    case VK_OBJECT_TYPE_SWAPCHAIN_KHR:
        return VK_DEBUG_REPORT_OBJECT_TYPE_SWAPCHAIN_KHR_EXT;
#ifdef VK_KHR_display
    case VK_OBJECT_TYPE_DISPLAY_KHR:
        return VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_KHR_EXT;
    case VK_OBJECT_TYPE_DISPLAY_MODE_KHR:
        return VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_MODE_KHR_EXT;
#endif
    case VK_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT:
        return VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT;
    case VK_OBJECT_TYPE_OBJECT_TABLE_NVX:
        return VK_DEBUG_REPORT_OBJECT_TYPE_OBJECT_TABLE_NVX_EXT;
    case VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVX:
        return VK_DEBUG_REPORT_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVX_EXT;
    case VK_OBJECT_TYPE_VALIDATION_CACHE_EXT:
        return VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT;
    case VK_OBJECT_TYPE_ACCELERATION_STRUCTURE_NV:
        return VK_DEBUG_REPORT_OBJECT_TYPE_ACCELERATION_STRUCTURE_NV_EXT;
    default:
        return VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT;
    }
}
} // namespace helpers
} // namespace magma
