/*
Magma - Abstraction layer over Khronos Vulkan API.
Copyright (C) 2018-2026 Victor Coda.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
*/
#pragma once

namespace magma
{
    class Buffer;

    /* Buffer memory barriers only apply to memory accesses
       involving a specific buffer range. That is, a memory
       dependency formed from an buffer memory barrier is scoped
       to access via the specified buffer range. Buffer memory
       barriers can also be used to define a queue family
       ownership transfer for the specified buffer range. */

    struct BufferMemoryBarrier : VkBufferMemoryBarrier
    {
        constexpr BufferMemoryBarrier(VkAccessFlags srcAccessMask,
            VkAccessFlags dstAccessMask) noexcept;
        BufferMemoryBarrier(const Buffer *buffer,
            VkAccessFlags srcAccessMask,
            VkAccessFlags dstAccessMask,
            VkDeviceSize offset = 0,
            VkDeviceSize size = VK_WHOLE_SIZE) noexcept;
        BufferMemoryBarrier(const Buffer *buffer,
            const BufferMemoryBarrier& barrier,
            VkDeviceSize offset = 0,
            VkDeviceSize size = VK_WHOLE_SIZE) noexcept;
    };
} // namespace magma

#include "bufferMemoryBarrier.inl"

namespace magma::barrier::buffer
{
    constexpr BufferMemoryBarrier hostWriteIndirectCommandRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_INDIRECT_COMMAND_READ_BIT);
    constexpr BufferMemoryBarrier hostWriteIndexRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_INDEX_READ_BIT);
    constexpr BufferMemoryBarrier hostWriteVertexAttributeRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT);
    constexpr BufferMemoryBarrier hostWriteUniformRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_UNIFORM_READ_BIT);
    constexpr BufferMemoryBarrier hostWriteShaderRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT);
    constexpr BufferMemoryBarrier hostWriteShaderWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier hostWriteShaderReadWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier hostWriteTransferRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT);
    constexpr BufferMemoryBarrier hostWriteTransferWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier hostWriteTransferReadWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier hostWriteRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_HOST_READ_BIT);
    constexpr BufferMemoryBarrier hostWriteWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier hostWriteReadWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_HOST_READ_BIT | VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier hostWriteMemoryRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_MEMORY_READ_BIT);
    constexpr BufferMemoryBarrier hostWriteMemoryWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier hostWriteMemoryReadWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT);

    constexpr BufferMemoryBarrier transferWriteIndirectCommandRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_INDIRECT_COMMAND_READ_BIT);
    constexpr BufferMemoryBarrier transferWriteIndexRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_INDEX_READ_BIT);
    constexpr BufferMemoryBarrier transferWriteVertexAttributeRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT);
    constexpr BufferMemoryBarrier transferWriteUniformRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_UNIFORM_READ_BIT);
    constexpr BufferMemoryBarrier transferWriteShaderRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT);
    constexpr BufferMemoryBarrier transferWriteShaderWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier transferWriteShaderReadWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier transferWriteRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT);
    constexpr BufferMemoryBarrier transferWriteWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier transferWriteReadWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier transferWriteHostRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_HOST_READ_BIT);
    constexpr BufferMemoryBarrier transferWriteHostWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier transferWriteHostReadWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_HOST_READ_BIT | VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier transferWriteMemoryRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_MEMORY_READ_BIT);
    constexpr BufferMemoryBarrier transferWriteMemoryWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier transferWriteMemoryReadWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT);

    constexpr BufferMemoryBarrier shaderWriteIndirectCommandRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_INDIRECT_COMMAND_READ_BIT);
    constexpr BufferMemoryBarrier shaderWriteIndexRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_INDEX_READ_BIT);
    constexpr BufferMemoryBarrier shaderWriteVertexAttributeRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT);
    constexpr BufferMemoryBarrier shaderWriteUniformRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_UNIFORM_READ_BIT);
    constexpr BufferMemoryBarrier shaderWriteRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT);
    constexpr BufferMemoryBarrier shaderWriteWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier shaderWriteReadWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier shaderWriteTransferRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT);
    constexpr BufferMemoryBarrier shaderWriteTransferWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier shaderWriteTransferReadWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier shaderWriteHostRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_HOST_READ_BIT);
    constexpr BufferMemoryBarrier shaderWriteHostWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier shaderWriteHostReadWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_HOST_READ_BIT | VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier shaderWriteMemoryRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_MEMORY_READ_BIT);
    constexpr BufferMemoryBarrier shaderWriteMemoryWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier shaderWriteMemoryReadWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT);

    constexpr BufferMemoryBarrier memoryWriteIndirectCommandRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_INDIRECT_COMMAND_READ_BIT);
    constexpr BufferMemoryBarrier memoryWriteIndexRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_INDEX_READ_BIT);
    constexpr BufferMemoryBarrier memoryWriteVertexAttributeRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT);
    constexpr BufferMemoryBarrier memoryWriteUniformRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_UNIFORM_READ_BIT);
    constexpr BufferMemoryBarrier memoryWriteShaderRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT);
    constexpr BufferMemoryBarrier memoryWriteShaderWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier memoryWriteShaderReadWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier memoryWriteTransferRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT);
    constexpr BufferMemoryBarrier memoryWriteTransferWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier memoryWriteTransferReadWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier memoryWriteHostRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_HOST_READ_BIT);
    constexpr BufferMemoryBarrier memoryWriteHostWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier memoryWriteHostReadWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_HOST_READ_BIT | VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier memoryWriteRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_MEMORY_READ_BIT);
    constexpr BufferMemoryBarrier memoryWriteWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier memoryWriteReadWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT);

#ifdef VK_EXT_conditional_rendering
    constexpr BufferMemoryBarrier hostWriteConditionalRenderingRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT);
    constexpr BufferMemoryBarrier transferWriteConditionalRenderingRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT);
    constexpr BufferMemoryBarrier shaderWriteConditionalRenderingRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT);
    constexpr BufferMemoryBarrier memoryWriteConditionalRenderingRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT);

    #ifdef VK_EXT_transform_feedback
    constexpr BufferMemoryBarrier transformFeedbackWriteConditionalRenderingRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteConditionalRenderingRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT);
    #endif // VK_EXT_conditional_rendering

    #ifdef VK_KHR_acceleration_structure
    constexpr BufferMemoryBarrier accelerationStructureWriteConditionalRenderingRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT);
    #endif // VK_KHR_acceleration_structure

    #ifdef VK_NV_device_generated_commands
    constexpr BufferMemoryBarrier commandPreprocessWriteConditionalRenderingRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT);
    #endif // VK_NV_device_generated_commands
#endif // VK_EXT_conditional_rendering

#ifdef VK_EXT_transform_feedback
    constexpr BufferMemoryBarrier hostWriteTransformFeedbackWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier hostWriteTransformFeedbackCounterRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT);
    constexpr BufferMemoryBarrier hostWriteTransformFeedbackCounterWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier hostWriteTransformFeedbackCounterReadWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT | VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);

    constexpr BufferMemoryBarrier transferWriteTransformFeedbackWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier transferWriteTransformFeedbackCounterRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT);
    constexpr BufferMemoryBarrier transferWriteTransformFeedbackCounterWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier transferWriteTransformFeedbackCounterReadWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT | VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);

    constexpr BufferMemoryBarrier shaderWriteTransformFeedbackWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier shaderWriteTransformFeedbackCounterRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT);
    constexpr BufferMemoryBarrier shaderWriteTransformFeedbackCounterWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier shaderWriteTransformFeedbackCounterReadWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT | VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);

    constexpr BufferMemoryBarrier memoryWriteTransformFeedbackWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier memoryWriteTransformFeedbackCounterRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT);
    constexpr BufferMemoryBarrier memoryWriteTransformFeedbackCounterWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier memoryWriteTransformFeedbackCounterReadWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT | VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);

    constexpr BufferMemoryBarrier transformFeedbackWriteIndirectCommandRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_INDIRECT_COMMAND_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteIndexRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_INDEX_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteVertexAttributeRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteUniformRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_UNIFORM_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteShaderRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_SHADER_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteShaderWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteShaderReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteTransferRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_TRANSFER_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteTransferWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteTransferReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteHostRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_HOST_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteHostWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteHostReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_HOST_READ_BIT | VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteMemoryRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_MEMORY_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteMemoryWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteMemoryReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackWriteWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier transformFeedbackWriteTransformFeedbackCounterRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT);
    constexpr BufferMemoryBarrier transformFeedbackWriteTransformFeedbackCounterWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier transformFeedbackWriteTransformFeedbackCounterReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT | VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);

    constexpr BufferMemoryBarrier transformFeedbackCounterWriteIndirectCommandRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_INDIRECT_COMMAND_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteIndexRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_INDEX_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteVertexAttributeRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteUniformRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_UNIFORM_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteShaderRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_SHADER_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteShaderWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteShaderReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteTransferRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_TRANSFER_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteTransferWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteTransferReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteHostRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_HOST_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteHostWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteHostReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_HOST_READ_BIT | VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteMemoryRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_MEMORY_READ_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteMemoryWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteMemoryReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteTransformFeedbackWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT | VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);

    #ifdef VK_KHR_acceleration_structure
    constexpr BufferMemoryBarrier transformFeedbackWriteAccelerationStructureRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR);
    constexpr BufferMemoryBarrier transformFeedbackWriteAccelerationStructureWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    constexpr BufferMemoryBarrier transformFeedbackWriteAccelerationStructureReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR | VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteAccelerationStructureRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteAccelerationStructureWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteAccelerationStructureReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR | VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    constexpr BufferMemoryBarrier accelerationStructureWriteTransformFeedbackWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier accelerationStructureWriteTransformFeedbackCounterRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT);
    constexpr BufferMemoryBarrier accelerationStructureWriteTransformFeedbackCounterWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier accelerationStructureWriteTransformFeedbackCounterReadWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT | VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);
    #endif // VK_KHR_acceleration_structure

    #ifdef VK_NV_device_generated_commands
    constexpr BufferMemoryBarrier transformFeedbackWriteCommandPreprocessRead(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV);
    constexpr BufferMemoryBarrier transformFeedbackWriteCommandPreprocessWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier transformFeedbackWriteCommandPreprocessReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV | VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteCommandPreprocessRead(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteCommandPreprocessWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier transformFeedbackCounterWriteCommandPreprocessReadWrite(VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV | VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier commandPreprocessWriteTransformFeedbackWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier commandPreprocessWriteTransformFeedbackCounterRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT);
    constexpr BufferMemoryBarrier commandPreprocessWriteTransformFeedbackCounterWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);
    constexpr BufferMemoryBarrier commandPreprocessWriteTransformFeedbackCounterReadWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT | VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT);
    #endif // VK_NV_device_generated_commands
#endif // VK_EXT_transform_feedback

#ifdef VK_KHR_acceleration_structure
    constexpr BufferMemoryBarrier hostWriteAccelerationStructureRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR);
    constexpr BufferMemoryBarrier hostWriteAccelerationStructureWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    constexpr BufferMemoryBarrier hostWriteAccelerationStructureReadWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR | VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);

    constexpr BufferMemoryBarrier transferWriteAccelerationStructureRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR);
    constexpr BufferMemoryBarrier transferWriteAccelerationStructureWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    constexpr BufferMemoryBarrier transferWriteAccelerationStructureReadWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR | VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);

    constexpr BufferMemoryBarrier shaderWriteAccelerationStructureRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR);
    constexpr BufferMemoryBarrier shaderWriteAccelerationStructureWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    constexpr BufferMemoryBarrier shaderWriteAccelerationStructureReadWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR | VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);

    constexpr BufferMemoryBarrier memoryWriteAccelerationStructureRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR);
    constexpr BufferMemoryBarrier memoryWriteAccelerationStructureWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    constexpr BufferMemoryBarrier memoryWriteAccelerationStructureReadWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR | VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);

    constexpr BufferMemoryBarrier accelerationStructureWriteIndirectCommandRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_INDIRECT_COMMAND_READ_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteIndexRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_INDEX_READ_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteVertexAttributeRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteUniformRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_UNIFORM_READ_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteShaderRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_SHADER_READ_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteShaderWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteShaderReadWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteTransferRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_TRANSFER_READ_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteTransferWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteTransferReadWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteHostRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_HOST_READ_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteHostWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteHostReadWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_HOST_READ_BIT | VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteMemoryRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_MEMORY_READ_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteMemoryWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteMemoryReadWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier accelerationStructureWriteRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR);
    constexpr BufferMemoryBarrier accelerationStructureWriteWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    constexpr BufferMemoryBarrier accelerationStructureWriteReadWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR | VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);

    #ifdef VK_NV_device_generated_commands
    constexpr BufferMemoryBarrier accelerationStructureWriteCommandPreprocessRead(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV);
    constexpr BufferMemoryBarrier accelerationStructureWriteCommandPreprocessWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier accelerationStructureWriteCommandPreprocessReadWrite(VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV | VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier commandPreprocessWriteAccelerationStructureRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR);
    constexpr BufferMemoryBarrier commandPreprocessWriteAccelerationStructureWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    constexpr BufferMemoryBarrier commandPreprocessWriteAccelerationStructureReadWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR | VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR);
    #endif // VK_NV_device_generated_commands
#endif // VK_KHR_acceleration_structure

#ifdef VK_NV_device_generated_commands
    constexpr BufferMemoryBarrier hostWriteCommandPreprocessRead(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV);
    constexpr BufferMemoryBarrier hostWriteCommandPreprocessWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier hostWriteCommandPreprocessReadWrite(VK_ACCESS_HOST_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV | VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);

    constexpr BufferMemoryBarrier transferWriteCommandPreprocessRead(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV);
    constexpr BufferMemoryBarrier transferWriteCommandPreprocessWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier transferWriteCommandPreprocessReadWrite(VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV | VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);

    constexpr BufferMemoryBarrier shaderWriteCommandPreprocessRead(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV);
    constexpr BufferMemoryBarrier shaderWriteCommandPreprocessWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier shaderWriteCommandPreprocessReadWrite(VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV | VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);

    constexpr BufferMemoryBarrier memoryWriteCommandPreprocessRead(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV);
    constexpr BufferMemoryBarrier memoryWriteCommandPreprocessWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier memoryWriteCommandPreprocessReadWrite(VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV | VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);

    constexpr BufferMemoryBarrier commandPreprocessWriteIndirectCommandRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_INDIRECT_COMMAND_READ_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteIndexRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_INDEX_READ_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteVertexAttributeRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteUniformRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_UNIFORM_READ_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteShaderRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_SHADER_READ_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteShaderWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteShaderReadWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteTransferRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_TRANSFER_READ_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteTransferWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteTransferReadWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteHostRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_HOST_READ_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteHostWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteHostReadWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_HOST_READ_BIT | VK_ACCESS_HOST_WRITE_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteMemoryRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_MEMORY_READ_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteMemoryWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteMemoryReadWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT);
    constexpr BufferMemoryBarrier commandPreprocessWriteRead(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV);
    constexpr BufferMemoryBarrier commandPreprocessWriteWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
    constexpr BufferMemoryBarrier commandPreprocessWriteReadWrite(VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV, VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV | VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV);
#endif // VK_NV_device_generated_commands
} // namespace magma::barrier::buffer
