// Generated by utility tool. DO NOT MODIFY!
// 1/(2^(exp - EXP_BIAS - MANTISSA_BITS))
constexpr float rcpExpPow2[MAX_VALID_BIASED_EXP + 1] = {
    16777216.f, 8388608.f, 4194304.f, 2097152.f, 1048576.f,
    524288.f, 262144.f, 131072.f, 65536.f,
    32768.f, 16384.f, 8192.f, 4096.f,
    2048.f, 1024.f, 512.f, 256.f,
    128.f, 64.f, 32.f, 16.f,
    8.f, 4.f, 2.f, 1.f,
    0.5f, 0.25f, 0.125f, 0.0625f,
    0.03125f, 0.015625f, 0.0078125f
};
